// Mocks generated by Mockito 5.0.15 from annotations
// in ifood/test/app/presentation/pokemon_detail/pokemon_detail_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:domain/model/pokemon_detail.dart' as _i3;
import 'package:domain/repository/pokemon_repository.dart' as _i2;
import 'package:domain/use_case/get_pokemon_detail_use_case.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakePokemonRepository_0 extends _i1.Fake
    implements _i2.PokemonRepository {}

class _FakePokemonDetail_1 extends _i1.Fake implements _i3.PokemonDetail {}

/// A class which mocks [GetPokemonDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonDetailUseCase extends _i1.Mock
    implements _i4.GetPokemonDetailUseCase {
  MockGetPokemonDetailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakePokemonRepository_0()) as _i2.PokemonRepository);
  @override
  _i5.Future<_i3.PokemonDetail> getRawFuture(
          _i4.GetPokemonDetailUseCaseParams? params) =>
      (super.noSuchMethod(Invocation.method(#getRawFuture, [params]),
              returnValue:
                  Future<_i3.PokemonDetail>.value(_FakePokemonDetail_1()))
          as _i5.Future<_i3.PokemonDetail>);
  @override
  _i5.Future<_i3.PokemonDetail> call(
          {_i4.GetPokemonDetailUseCaseParams? params = null}) =>
      (super.noSuchMethod(Invocation.method(#call, [], {#params: params}),
              returnValue:
                  Future<_i3.PokemonDetail>.value(_FakePokemonDetail_1()))
          as _i5.Future<_i3.PokemonDetail>);
  @override
  String toString() => super.toString();
}
